import { defineEventHandler, readBody } from 'h3'
import type { EntityModel } from '~/types/template'

export default defineEventHandler(async (event) => {
  const body = await readBody<{ prompt: string }>(event)
  const prompt = body?.prompt?.trim()

  if (!prompt) {
    throw createError({
      statusCode: 400,
      statusMessage: 'Prompt is required'
    })
  }

  const apiKey = process.env.GEMINI_API_KEY || ''

  if (apiKey) {
    try {
      // Use Google GenAI official SDK or direct endpoint
      const { GoogleGenAI } = await import('@google/genai')
      const ai = new GoogleGenAI({ apiKey })

      const systemInstruction = `You are an expert full-stack database architect. 
Given a user's business description in Thai or English, output a JSON array of database entities.
Each entity must have:
- id: string (lowercase slug)
- name: string (PascalCase singular, e.g. "Product", "Appointment")
- label: string (readable label with Thai translation if prompt is Thai)
- fields: array of fields with:
  - id: string
  - name: string (camelCase)
  - type: 'string' | 'int' | 'decimal' | 'boolean' | 'datetime' | 'text'
  - required: boolean
  - isUnique: boolean (optional)
  - defaultValue: string (optional)
  - label: string

Do NOT include generic id, createdAt, or updatedAt fields as they are automatically generated by the engine.
Output ONLY valid JSON array with no markdown ticks.`

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
          systemInstruction,
          responseMimeType: 'application/json'
        }
      })

      const text = response.text || ''
      const parsed = JSON.parse(text)
      if (Array.isArray(parsed) && parsed.length > 0) {
        return {
          success: true,
          source: 'gemini-ai',
          entities: parsed
        }
      }
    } catch (err: any) {
      console.warn('Gemini API call failed, falling back to smart schema generator:', err?.message || err)
    }
  }

  // Smart Domain Fallback Generator (Deterministic AI simulation)
  const entities = generateSmartFallbackEntities(prompt)
  return {
    success: true,
    source: 'smart-domain-engine',
    entities
  }
})

function generateSmartFallbackEntities(prompt: string): EntityModel[] {
  const p = prompt.toLowerCase()

  if (p.includes('สัตว์') || p.includes('pet') || p.includes('คลินิก') || p.includes('clinic')) {
    return [
      {
        id: 'patient',
        name: 'Patient',
        label: 'สัตว์เลี้ยง / ผู้ป่วย (Patients)',
        fields: [
          { id: 'p1', name: 'name', type: 'string', required: true, label: 'ชื่อสัตว์เลี้ยง' },
          { id: 'p2', name: 'species', type: 'string', required: true, defaultValue: "'สุนัข'", label: 'สายพันธุ์' },
          { id: 'p3', name: 'age', type: 'int', required: true, defaultValue: '2', label: 'อายุ (ปี)' },
          { id: 'p4', name: 'ownerName', type: 'string', required: true, label: 'ชื่อเจ้าของ' },
          { id: 'p5', name: 'ownerPhone', type: 'string', required: true, label: 'เบอร์ติดต่อเจ้าของ' }
        ]
      },
      {
        id: 'appointment',
        name: 'Appointment',
        label: 'การนัดหมาย (Appointments)',
        fields: [
          { id: 'a1', name: 'appointmentDate', type: 'datetime', required: true, label: 'วันเวลานัด' },
          { id: 'a2', name: 'symptoms', type: 'text', required: true, label: 'อาการเบื้องต้น' },
          { id: 'a3', name: 'doctor', type: 'string', required: true, label: 'สัตวแพทย์ผู้ตรวจ' },
          { id: 'a4', name: 'status', type: 'string', required: true, defaultValue: "'นัดหมายแล้ว'", label: 'สถานะ' }
        ]
      },
      {
        id: 'medical_record',
        name: 'MedicalRecord',
        label: 'บันทึกการรักษา (Medical Records)',
        fields: [
          { id: 'm1', name: 'diagnosis', type: 'string', required: true, label: 'ผลการวินิจฉัย' },
          { id: 'm2', name: 'treatment', type: 'text', required: true, label: 'การรักษาและยาที่จ่าย' },
          { id: 'm3', name: 'fee', type: 'decimal', required: true, defaultValue: '500.00', label: 'ค่ารักษา (บาท)' }
        ]
      }
    ]
  }

  if (p.includes('กาแฟ') || p.includes('coffee') || p.includes('ร้านอาหาร') || p.includes('restaurant') || p.includes('cafe')) {
    return [
      {
        id: 'menu_item',
        name: 'MenuItem',
        label: 'เมนูอาหาร/เครื่องดื่ม (Menu Items)',
        fields: [
          { id: 'm1', name: 'name', type: 'string', required: true, label: 'ชื่อเมนู' },
          { id: 'm2', name: 'category', type: 'string', required: true, defaultValue: "'เครื่องดื่ม'", label: 'หมวดหมู่' },
          { id: 'm3', name: 'price', type: 'decimal', required: true, defaultValue: '65.00', label: 'ราคา (บาท)' },
          { id: 'm4', name: 'isAvailable', type: 'boolean', required: true, defaultValue: 'true', label: 'พร้อมจำหน่าย' }
        ]
      },
      {
        id: 'order',
        name: 'Order',
        label: 'ออเดอร์คำสั่งซื้อ (Orders)',
        fields: [
          { id: 'o1', name: 'tableNumber', type: 'string', required: true, defaultValue: "'T-01'", label: 'โต๊ะ/ช่องทาง' },
          { id: 'o2', name: 'totalPrice', type: 'decimal', required: true, label: 'ยอดรวม' },
          { id: 'o3', name: 'paymentMethod', type: 'string', required: true, defaultValue: "'PromptPay'", label: 'วิธีชำระเงิน' },
          { id: 'o4', name: 'status', type: 'string', required: true, defaultValue: "'Preparing'", label: 'สถานะออเดอร์' }
        ]
      },
      {
        id: 'inventory',
        name: 'Inventory',
        label: 'วัตถุดิบคงคลัง (Inventory)',
        fields: [
          { id: 'i1', name: 'itemName', type: 'string', required: true, label: 'ชื่อวัตถุดิบ' },
          { id: 'i2', name: 'quantity', type: 'decimal', required: true, label: 'จำนวนคงเหลือ' },
          { id: 'i3', name: 'unit', type: 'string', required: true, defaultValue: "'kg'", label: 'หน่วยนับ' }
        ]
      }
    ]
  }

  if (p.includes('โรงเรียน') || p.includes('school') || p.includes('course') || p.includes('คอร์ส') || p.includes('นักเรียน')) {
    return [
      {
        id: 'course',
        name: 'Course',
        label: 'คอร์สเรียน (Courses)',
        fields: [
          { id: 'c1', name: 'title', type: 'string', required: true, label: 'ชื่อคอร์ส' },
          { id: 'c2', name: 'instructor', type: 'string', required: true, label: 'ผู้สอน' },
          { id: 'c3', name: 'price', type: 'decimal', required: true, label: 'ราคาคอร์ส' },
          { id: 'c4', name: 'hours', type: 'int', required: true, defaultValue: '20', label: 'ชั่วโมงเรียน' }
        ]
      },
      {
        id: 'student',
        name: 'Student',
        label: 'ข้อมูลนักเรียน (Students)',
        fields: [
          { id: 's1', name: 'fullName', type: 'string', required: true, label: 'ชื่อ-นามสกุล' },
          { id: 's2', name: 'email', type: 'string', required: true, isUnique: true, label: 'อีเมล' },
          { id: 's3', name: 'phoneNumber', type: 'string', required: false, label: 'เบอร์โทร' }
        ]
      },
      {
        id: 'enrollment',
        name: 'Enrollment',
        label: 'การลงทะเบียน (Enrollments)',
        fields: [
          { id: 'e1', name: 'enrolledDate', type: 'datetime', required: true, label: 'วันที่ลงทะเบียน' },
          { id: 'e2', name: 'paymentStatus', type: 'string', required: true, defaultValue: "'Paid'", label: 'สถานะชำระเงิน' },
          { id: 'e3', name: 'progressPercentage', type: 'int', required: true, defaultValue: '0', label: 'ความคืบหน้า (%)' }
        ]
      }
    ]
  }

  // Default Universal Schema for any input
  const words = prompt.split(/\s+/).filter(w => w.length > 1)
  const mainSubject = words[0] ? words[0].replace(/[^a-zA-Zก-๙]/g, '') : 'Item'

  return [
    {
      id: 'main_item',
      name: 'MainItem',
      label: `รายการหลัก (${mainSubject || 'Items'})`,
      fields: [
        { id: 'f1', name: 'title', type: 'string', required: true, label: 'ชื่อรายการ' },
        { id: 'f2', name: 'code', type: 'string', required: true, isUnique: true, label: 'รหัสอ้างอิง' },
        { id: 'f3', name: 'status', type: 'string', required: true, defaultValue: "'Active'", label: 'สถานะ' },
        { id: 'f4', name: 'description', type: 'text', required: false, label: 'รายละเอียด' }
      ]
    },
    {
      id: 'transaction',
      name: 'Transaction',
      label: 'บันทึกธุรกรรม (Transactions)',
      fields: [
        { id: 't1', name: 'referenceNo', type: 'string', required: true, isUnique: true, label: 'เลขที่เอกสาร' },
        { id: 't2', name: 'amount', type: 'decimal', required: true, label: 'ยอดเงิน' },
        { id: 't3', name: 'transactionDate', type: 'datetime', required: true, label: 'วันที่ทำรายการ' }
      ]
    }
  ]
}
