import type { TemplateConfig, GeneratedFile } from '~/types/template'

export function generateDockerFiles(config: TemplateConfig): GeneratedFile[] {
  const files: GeneratedFile[] = []
  const projectName = config.projectName || 'FullStackApp'
  const isPostgres = config.database === 'postgres'
  const isMysql = config.database === 'mysql'
  const isSqlServer = config.database === 'sqlserver'

  let dbService = ''
  let backendEnv = ''

  if (isPostgres) {
    dbService = `  postgres:
    image: postgres:16-alpine
    container_name: \${COMPOSE_PROJECT_NAME:-app}-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data`

    backendEnv = `      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=appdb;Username=postgres;Password=postgrespassword;
      - DATABASE_URL=postgresql://postgres:postgrespassword@postgres:5432/appdb?schema=public`
  } else if (isMysql) {
    dbService = `  mysql:
    image: mysql:8.0
    container_name: \${COMPOSE_PROJECT_NAME:-app}-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql`

    backendEnv = `      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=appdb;User=root;Password=rootpassword;
      - DATABASE_URL=mysql://root:rootpassword@mysql:3306/appdb`
  } else if (isSqlServer) {
    dbService = `  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: \${COMPOSE_PROJECT_NAME:-app}-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql`

    backendEnv = `      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=appdb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - DATABASE_URL=sqlserver://sqlserver:1433;database=appdb;user=sa;password=YourStrong@Passw0rd;encrypt=true;trustServerCertificate=true;`
  }

  // docker-compose.yml
  files.push({
    path: 'docker-compose.yml',
    content: `version: '3.8'

services:
${dbService}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: \${COMPOSE_PROJECT_NAME:-app}-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
${backendEnv}
    depends_on:
      - ${config.database}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: \${COMPOSE_PROJECT_NAME:-app}-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  ${config.database}_data:
`
  })

  // README.md
  files.push({
    path: 'README.md',
    content: `# ${projectName}

> Generated by **StackForge Studio** with ${config.backend === 'dotnet' ? 'ASP.NET Core 8 (.NET 8)' : 'NestJS'} + ${config.frontend === 'vue' ? 'Vue 3' : 'React'} + ${config.database.toUpperCase()} + Docker.

---

## 🚀 Quick Start with Docker (Recommended)

Run the entire stack with a single command:

\`\`\`bash
docker compose up --build
\`\`\`

Once booted, open your browser:
- 🌐 **Frontend Web App & Dashboard**: [http://localhost:3000](http://localhost:3000)
- 🔌 **Backend API & Swagger Docs**: [http://localhost:8080/swagger](http://localhost:8080/swagger)
- 🗄️ **Database (${config.database.toUpperCase()})**: Port ${isPostgres ? '5432' : isMysql ? '3306' : '1433'}

---

## 🛠 Local Development Setup

### 1. Database
Make sure you have ${config.database.toUpperCase()} running, or spin it up using Docker:
\`\`\`bash
docker compose up ${config.database} -d
\`\`\`

### 2. Backend (${config.backend === 'dotnet' ? '.NET 8 Web API' : 'NestJS'})
\`\`\`bash
cd backend
${config.backend === 'dotnet' ? 'dotnet restore\ndotnet run' : 'npm install\nnpm run start:dev'}
\`\`\`

### 3. Frontend (${config.frontend === 'vue' ? 'Vue 3 + Vite' : 'React + Vite'})
\`\`\`bash
cd frontend
npm install
npm run dev
\`\`\`
Visit [http://localhost:3000](http://localhost:3000)

---

## 📦 Generated Entities & End-to-End CRUD
${config.entities.map(e => `- **${e.name}** (${e.label || e.name}): \`/api/${e.name.toLowerCase()}s\` & Frontend \`/${e.name.toLowerCase()}s\``).join('\n')}

Enjoy building your application!
`
  })

  // .gitignore
  files.push({
    path: '.gitignore',
    content: `node_modules/
dist/
bin/
obj/
*.user
*.suo
.vs/
.idea/
.vscode/
*.local
.env
`
  })

  return files
}
